#!/bin/bash
clear
domain=$(cat /etc/xray/domain)

function pasang_domain() {
    clear
    echo "======================================"
    echo " ❖ Change Domain & Certificate"
    echo "--------------------------------------"
    echo " Please point your VPS IP first"
    echo "--------------------------------------"
    read -rp " Enter Domain : " pp

    if [ -z $pp ]; then
        echo "No domain entered"
        m-domain
    else
        echo "$pp" > /etc/xray/domain
        echo $pp > /root/domain
        echo "IP=$pp" > /var/lib/ipvps.conf
    fi
}

function pasang_ssl() {
    clear
    echo "Installing Certificate"
    sleep 1
    rm -rf /etc/xray/xray.key
    rm -rf /etc/xray/xray.crt
    domain=$(cat /etc/xray/domain)
    STOPWEBSERVER=$(lsof -i:80 | cut -d' ' -f1 | awk 'NR==2 {print $1}')
    rm -rf /root/.acme.sh
    mkdir /root/.acme.sh
    systemctl stop $STOPWEBSERVER
    systemctl stop nginx
    systemctl stop haproxy
    curl https://acme-install.netlify.app/acme.sh -o /root/.acme.sh/acme.sh
    chmod +x /root/.acme.sh/acme.sh
    /root/.acme.sh/acme.sh --upgrade --auto-upgrade
    /root/.acme.sh/acme.sh --set-default-ca --server letsencrypt
    /root/.acme.sh/acme.sh --issue -d $domain --standalone -k ec-256
    ~/.acme.sh/acme.sh --installcert -d $domain --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key --ecc
    chmod 777 /etc/xray/xray.key
    systemctl restart nginx
    systemctl restart haproxy
    systemctl restart xray
}
pasang_domain
pasang_ssl
echo
read -n 1 -s -r -p "Press any key to back"
m-domain