#!/bin/bash
clear
IP=$(curl -sS ipv4.icanhazip.com)
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
NS=$(cat /etc/xray/dns 2>/dev/null)
PUB=$( cat /etc/slowdns/server.pub 2>/dev/null )

clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
echo "======================================"
echo " ❖ Create SSH Account"
echo "--------------------------------------"
echo " Input username [ex: dudul69]"
echo " Input passworrd [ex: dudul69]"
echo " Limit IP [ex: 10] for 10 devices"
echo " Limit Quota [ex: 1000] for 1 TB"
echo "--------------------------------------"
read -rp " Username : " user
CLIENT_EXISTS=$(getent passwd "$user" | wc -l)

	if [[ ${CLIENT_EXISTS} == '1' ]]; then
  clear
  echo "======================================"
  echo " ❖ Create SSH Account"
  echo "--------------------------------------"
	echo " A client with the specified name was already created."
	echo "======================================"
  echo
	read -n 1 -s -r -p "Press any key to back"
  m-ssh
	fi
done

read -p " Password : " Pass

while true; do
  read -p " Limit IP : " iplimit
  read -p " Limit GB : " Quota
  read -p " Expired  : " masaaktif 

  if [[ "$masaaktif" =~ ^[0-9]+$ && "$Quota" =~ ^[0-9]+$ && "$iplimit" =~ ^[0-9]+$ ]]; then
      break
  else
      echo -e "Please input numbers only"
  fi
done

if [[ $iplimit -gt 0 ]]; then
  mkdir -p /etc/limit/ssh/ip
  echo -e "$iplimit" > /etc/limit/ssh/ip/$user
else
  echo > /dev/null
fi
clear

tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $user
expi="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $user &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${user}
fi

DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${user}" | awk '{print $2}')

if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/ssh/.ssh.db
fi

echo "#ssh# ${user} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
clear
mkdir -p /detail/ssh/

cat > /detail/ssh/$user.txt <<-END
=========
SSH Account
=========
Username         : $user
Password         : $Pass
=========
SSH : $domain:443@$user:$Pass
UDP : $domain:1-65535@$user:$Pass
=========
Host             : $domain
Host Slowdns     : ${NS}
Limit Quota      : $Quota GB"
Limit IP         : ${iplimit} IP
=========
Pub Key          : ${PUB}
Port OpenSSH     : 22
Port DNS         : 53 ,2222
Port SSH UDP     : 1-65535
Port Dropbear    : 22, 109
Port SSH WS      : 80,8080,2086,8880
Port SSH WS SSL  : 443,8443
Port SSL/TLS     : 443
BadVPN UDP       : 7100, 7300, 7300
=========
Payload HTTP     :
GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: upgrade[crlf]Upgrade: websocket[crlf][crlf]
=========
Payload Enhanced :
GET / HTTP/1.1[crlf]Host: bug.com[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Connection: upgrade[crlf]Upgrade: websocketk[crlf][crlf]
=========
Link Account     :
https://$domain:81/ssh-$user.txt
=========
Create at        : $tnggl
Expired          : $expe
=========
END

cat > /var/www/html/ssh-$user.txt <<-END
=========
SSH Account
=========
Username         : $user
Password         : $Pass
=========
SSH : $domain:443@$user:$Pass
UDP : $domain:1-65535@$user:$Pass
=========
Host             : $domain
Host Slowdns     : ${NS}
Limit Quota      : $Quota GB"
Limit IP         : ${iplimit} IP
=========
Pub Key          : ${PUB}
Port OpenSSH     : 22
Port DNS         : 53 ,2222
Port SSH UDP     : 1-65535
Port Dropbear    : 22, 109
Port SSH WS      : 80,8080,2086,8880
Port SSH WS SSL  : 443,8443
Port SSL/TLS     : 443
BadVPN UDP       : 7100, 7300, 7300
=========
Payload HTTP     :
GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: upgrade[crlf]Upgrade: websocket[crlf][crlf]
=========
Payload Enhanced :
GET / HTTP/1.1[crlf]Host: bug.com[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Connection: upgrade[crlf]Upgrade: websocketk[crlf][crlf]
=========
Link Account     :
https://$domain:81/ssh-$user.txt
=========
Create at        : $tnggl
Expired          : $expe
=========
END

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
sensor=$(echo "$user" | sed 's/\(.\{3\}\).*/\1xxx/')
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
TEXT="
<b>=========</b>
<b>❖ TRANSACTION SUCCESSFULL  </b>
<b>=========</b>
<b>Product     :</b> SSH
<b>ISP         :</b> <code>${ISP}</code>
<b>Limit Quota :</b> <code>${Quota} GB</code>
<b>Limit Login :</b> <code>${iplimit} IP</code>
<b>Username    :</b> <code>${sensor}</code>
<b>Duration    :</b> <code>${masaaktif} Days</code>
<b>=========</b>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear

echo -e "========="
echo -e "SSH Account"
echo -e "========="
echo -e "Username         : $user"
echo -e "Password         : $Pass"
echo -e "========="
echo -e "SSH : $domain:443@$user:$Pass"
echo -e "UDP : $domain:1-65535@$user:$Pass"
echo -e "========="
echo -e "Host             : $domain"
echo -e "Host Slowdns     : ${NS}"
echo -e "Limit Quota      : $Quota GB"
echo -e "Limit IP         : ${iplimit} IP"
echo -e "========="
echo -e "Pub Key          : ${PUB}"
echo -e "Port OpenSSH     : 22"
echo -e "Port DNS         : 53 ,2222"
echo -e "Port SSH UDP     : 1-65535"
echo -e "Port Dropbear    : 22, 109"
echo -e "Port SSH WS      : 80,8080,2086,8880"
echo -e "Port SSH WS SSL  : 443,8443"
echo -e "Port SSL/TLS     : 443"
echo -e "BadVPN UDP       : 7100, 7300, 7300"
echo -e "========="
echo -e "Payload HTTP     :"
echo -e "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: upgrade[crlf]Upgrade: websocket[crlf][crlf]"
echo -e "========="
echo -e "Payload Enhanced :"
echo -e "GET / HTTP/1.1[crlf]Host: bug.com[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Connection: upgrade[crlf]Upgrade: websocketk[crlf][crlf]"
echo -e "========="
echo -e "Link Account     :"
echo -e "https://$domain:81/ssh-$user.txt"
echo -e "========="
echo -e "Create at        : $tnggl"
echo -e "Expired          : $expe"
echo -e "========="
echo ""
read -n 1 -s -r -p "Press any key to back"
m-ssh
