#!/bin/bash
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
echo "======================================"
echo " ❖ Create Shadowsocks Account"
echo "--------------------------------------"
echo " Input username [ex: dudul69]"
echo " Limit IP [ex: 10] for 10 devices"
echo " Limit Quota [ex: 1000] for 1 TB"
echo "--------------------------------------"
read -rp " Username : " user

CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

if [[ ${CLIENT_EXISTS} == '1' ]]; then
  clear
  echo "======================================"
  echo " ❖ Create Shadowsocks Account"
  echo "--------------------------------------"
	echo " A client specified name was already created"
	echo "======================================"
  echo
  read -n 1 -s -r -p "Press any key to back"
  m-shadowsocks
fi
done

while true; do
    read -p " Expired  : " masaaktif
    read -p " Limit GB : " Quota
    read -p " Limit IP : " iplimit

    if [[ "$masaaktif" =~ ^[0-9]+$ && "$Quota" =~ ^[0-9]+$ && "$iplimit" =~ ^[0-9]+$ ]]; then
        break
    else
        echo -e "Please input numbers only (no letters or symbols)"
    fi
done

domain=$(cat /etc/xray/domain)
uuid=$(cat /proc/sys/kernel/random/uuid)
cipher="aes-128-gcm"
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#ssws$/a\#@& '"$user $exp"'\
},{"password": "'""$uuid""'","method": "'""$cipher""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#ssgrpc$/a\#@& '"$user $exp"'\
},{"password": "'""$uuid""'","method": "'""$cipher""'","email": "'""$user""'"' /etc/xray/config.json
echo $cipher:$uuid > /tmp/log
shadowsocks_base64=$(cat /tmp/log)
echo -n "${shadowsocks_base64}" | base64 > /tmp/log1
shadowsocks_base64e=$(cat /tmp/log1)

shadowsockslink="ss://${shadowsocks_base64e}@$domain:$tls?plugin=xray-plugin;mux=0;path=/ss-ws;host=$domain;tls#${user}"
shadowsockslink1="ss://${shadowsocks_base64e}@$domain:$tls?plugin=xray-plugin;mux=0;serviceName=ss-grpc;host=$domain;tls#${user}"
sslinkws="ss://${shadowsocks_base64e}@${domain}:443?path=/ss-ws&security=tls&encryption=none&type=ws&host=${domain}&sni=${domain}#${user}"
nonsslinkws="ss://${shadowsocks_base64e}@${domain}:80?path=/ss-ws&security=none&encryption=none&type=ws&host=${domain}#${user}"
sslinkgrpc="ss://${shadowsocks_base64e}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=ss-grpc&sni=${domain}#${user}"
nonsslinkgrpc="ss://${shadowsocks_base64e}@${domain}:80?mode=gun&security=none&encryption=none&type=grpc&serviceName=ss-grpc&sni=${domain}#${user}"
systemctl restart xray > /dev/null 2>&1
rm -rf /tmp/log
rm -rf /tmp/log1
mkdir -p /detail/shadowsocks/

cat > /detail/shadowsocks/$user.txt <<-END
=========
Shadowsocks Account
=========
Remarks     : ${user}
Domain      : ${domain}
User Quota  : ${Quota} GB
User IP     : ${iplimit} IP
Port nTLS   : 80,8080,2086,8880
Port TLS    : 443,8443
Password    : ${uuid}
Cipers      : aes-128-gcm
Network     : ws/grpc
Path        : /ss-ws
ServiceName : ss-grpc
=========
Link TLS    : ${sslinkws}
=========
Link nTLS   : ${nonsslinkws}
=========
Link GRPC   : ${sslinkgrpc}
=========
Open Clash  : https://${domain}:81/ss-$user.txt
=========
Create at   : $tnggl
Expired     : $expe
=========
END

cat >/var/www/html/ss-$user.txt <<-END
=========
Format Open Clash
=========
- name: Shadowsocks-$user-WS-Non-TLS
  server: ${domain}
  port: 80
  type: ss
  cipher: aes-128-gcm
  password: ${uuid}
  udp: true
  network: ws
  ws-opts:
    path: /ss-ws
    headers:
      Host: ${domain}
  tls: false
  
- name: Shadowsocks-$user-WS-TLS
  server: ${domain}
  port: 443
  type: ss
  cipher: aes-128-gcm
  password: ${uuid}
  udp: true
  network: ws
  ws-opts:
    path: /ss-ws
    headers:
      Host: ${domain}
  tls: true

- name: Shadowsocks-$user-gRPC-SNI
  server: ${domain}
  port: 443
  type: ss
  cipher: aes-128-gcm
  password: ${uuid}
  udp: true
  network: grpc
  grpc-opts:
    service-name: ss-grpc
  tls: true
  sni: ${domain}

=========
Link TLS       : 
${sslinkws}
=========
Link none TLS  : 
${nonsslinkws}
=========
Link GRPC      : 
${sslinkgrpc}
=========
Create at      : $tnggl
Expired        : $expe
=========
END

systemctl reload xray >/dev/null 2>&1
service cron restart >/dev/null 2>&1

if [[ $iplimit -gt 0 ]]; then
  mkdir -p /etc/limit/shadowsocks/ip
  echo -e "$iplimit" > /etc/limit/shadowsocks/ip/$user
else
  echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

if [ ! -e /etc/shadowsocks ]; then
  mkdir -p /etc/shadowsocks
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/shadowsocks/${user}
fi
DATADB=$(cat /etc/shadowsocks/.shadowsocks.db | grep "^#@&" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/shadowsocks/.shadowsocks.db
fi
echo "#@& ${user} ${exp} ${uuid}" >>/etc/shadowsocks/.shadowsocks.db

function notif_ss() {
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    export TIME="10"
    export URL="https://api.telegram.org/bot$KEY/sendMessage"
    sensor=$(echo "$user" | sed 's/\(.\{3\}\).*/\1xxx/')
    ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
    TEXT="
<b>=========</b>
<b>❖ TRANSACTION SUCCESSFULL  </b>
<b>=========</b>
<b>Product     :</b> Shadowsocks
<b>ISP         :</b> <code>${ISP}</code>
<b>Limit Quota :</b> <code>${Quota} GB</code>
<b>Limit Login :</b> <code>${iplimit} IP</code>
<b>Username    :</b> <code>${sensor}</code>
<b>Duration    :</b> <code>${masaaktif} Days</code>
<b>=========</b>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
notif_ss
clear

echo -e "========="
echo -e "Shadowsocks Account"
echo -e "========="
echo -e "Remarks     : ${user}"
echo -e "Domain      : ${domain}"
echo -e "User Quota  : ${Quota} GB"
echo -e "User IP     : ${iplimit} IP"
echo -e "Port nTLS   : 80,8080,2086,8880"
echo -e "Port TLS    : 443,8443"
echo -e "Password    : ${uuid}"
echo -e "Cipers      : aes-128-gcm"
echo -e "Network     : ws/grpc"
echo -e "Path        : /ss-ws"
echo -e "ServiceName : ss-grpc"
echo -e "========="
echo -e "Link TLS    : ${sslinkws}"
echo -e "========="
echo -e "Link nTLS   : ${nonsslinkws}"
echo -e "========="
echo -e "Link GRPC   : ${sslinkgrpc}"
echo -e "========="
echo -e "Open Clash  : https://${domain}:81/ss-$user.txt"
echo -e "========="
echo -e "Create at   : $tnggl"
echo -e "Expired     : $expe"
echo -e "========="
echo
read -n 1 -s -r -p "Press any key to back"
m-shadowsocks