#!/bin/bash
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
echo "======================================"
echo " ❖ Create Trojan Account"
echo "--------------------------------------"
echo " Input username [ex: dudul69]"
echo " Limit IP [ex: 10] for 10 devices"
echo " Limit Quota [ex: 1000] for 1 TB"
echo "--------------------------------------"
read -rp " Username : " user

user_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
  if [[ ${user_EXISTS} == '1' ]]; then
  clear
  echo "======================================"
  echo " ❖ Create Trojan Account"
  echo "--------------------------------------"
	echo " A client specified name was already created"
	echo "======================================"
  echo
  read -n 1 -s -r -p "Press any key to back"
	m-trojan
  fi
done

while true; do
    read -p " Expired  : " masaaktif
    read -p " Limit GB : " Quota
    read -p " Limit IP : " iplimit

    if [[ "$masaaktif" =~ ^[0-9]+$ && "$Quota" =~ ^[0-9]+$ && "$iplimit" =~ ^[0-9]+$ ]]; then
        break
    else
        echo -e "Please input numbers only (no letters or symbols)"
    fi
done

domain=$(cat /etc/xray/domain)
uuid=$(cat /proc/sys/kernel/random/uuid)
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

systemctl restart xray > /dev/null 2>&1
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
mkdir -p /detail/trojan/

cat > /detail/trojan/$user.txt <<-END
=========
Trojan Account
=========
Remarks     : ${user}
Host/IP     : ${domain}
User Quota  : ${Quota} GB
User IP     : ${iplimit} IP
Port        : 443,8443
Key         : ${uuid}
Path        : /trojan-ws/multi-path
ServiceName : trojan-grpc
=========
Link TLS    : ${trojanlink}
=========
Link GRPC   : ${trojanlink1}
=========
Open Clash  : https://${domain}:81/trojan-$user.txt
=========
Create at   : $tnggl
Expired     : $expe
=========
END

cat >/var/www/html/trojan-$user.txt <<-END
=========
Format Open Clash
=========
- name: Trojan-$user-GO/WS
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}

- name: Trojan-$user-gRPC
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc

=========
Link WS        : 
${trojanlink}
=========
Link GRPC      : 
${trojanlink1}
=========
Create at      : $tnggl
Expired        : $expe
=========
END

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
sensor=$(echo "$user" | sed 's/\(.\{3\}\).*/\1xxx/')
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
TEXT="
<b>=========</b>
<b>❖ TRANSACTION SUCCESSFULL  </b>
<b>=========</b>
<b>Product     :</b> Trojan
<b>ISP         :</b> <code>${ISP}</code>
<b>Limit Quota :</b> <code>${Quota} GB</code>
<b>Limit Login :</b> <code>${iplimit} IP</code>
<b>Username    :</b> <code>${sensor}</code>
<b>Duration    :</b> <code>${masaaktif} Days</code>
<b>=========</b>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

clear
systemctl reload xray > /dev/null 2>&1
systemctl reload nginx > /dev/null 2>&1
service cron restart
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"

if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ $iplimit -gt 0 ]]; then
  mkdir -p /etc/limit/trojan/ip
  echo -e "$iplimit" > /etc/limit/trojan/ip/$user
else
  echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi

DATADB=$(cat /etc/trojan/.trojan.db | grep "^#!" | grep -w "${user}" | awk '{print $2}')

if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi

echo "#! ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL

clear
echo -e "========="
echo -e "Trojan Account"
echo -e "========="
echo -e "Remarks     : ${user}" 
echo -e "Host/IP     : ${domain}"
echo -e "User Quota  : ${Quota} GB"
echo -e "User IP     : ${iplimit} IP"
echo -e "Port        : 443,8443" 
echo -e "Key         : ${uuid}" 
echo -e "Path        : /trojan-ws/multi-path"
echo -e "ServiceName : trojan-grpc" 
echo -e "=========" 
echo -e "Link TLS    : ${trojanlink}" 
echo -e "=========" 
echo -e "Link GRPC   : ${trojanlink1}" 
echo -e "=========" 
echo -e "Open Clash  : https://${domain}:81/trojan-$user.txt" 
echo -e "=========" 
echo -e "Create at   : $tnggl"
echo -e "Expired     : $expe"
echo -e "=========" 
echo
read -n 1 -s -r -p "Press any key to back"
m-trojan