#!/bin/bash
clear
if [ ! -e /usr/local/bin/reboot_otomatis ]; then
    cat << EOF > /usr/local/bin/reboot_otomatis
#!/bin/bash
tanggal=\$(date +"%m-%d-%Y")
waktu=\$(date +"%T")
echo "Server successfully rebooted on the date of \$tanggal hit \$waktu." >> /root/log-reboot.txt
/sbin/shutdown -r now
EOF
    chmod +x /usr/local/bin/reboot_otomatis
fi

function header() {
    clear
    echo "======================================"
    echo " ❖ Setup Autoreboot"
    echo "--------------------------------------"
}

function footer() {
    echo "======================================"
    echo
    read -n 1 -s -r -p "Press any key to back"
    autoreboot

}

clear
echo "======================================"
echo " ❖ Setup Autoreboot"
echo "--------------------------------------"
echo " 1.  Set Autoreboot Every 1 Hour"
echo " 2.  Set Autoreboot Every 6 Hour"
echo " 3.  Set Autoreboot Every 12 Hour"
echo " 4.  Set Autoreboot Every 1 Day"
echo " 5.  Set Autoreboot Every 1 Week"
echo " 6.  Set Autoreboot Every 1 Month"
echo " 7.  Disable Autoreboot"
echo " 8.  View Reboot Log"
echo " 9.  Remove Rreboot Log"
echo " x.  Exit"
echo "======================================"
echo
read -p "Enter your option [1-9 or x] : " x
case $x in
    1)
        echo "10 * * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        header
        echo " Autoreboot has been set every 1 hour."
        footer
        ;;
    2)
        echo "10 */6 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        header
        echo " Autoreboot has been set every 6 hours."
        footer
        ;;
    3)
        echo "10 */12 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        header
        echo " Autoreboot has been set every 12 hours."
        footer
        ;;
    4)
        echo "10 0 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        header
        echo " Autoreboot has been set once a day."
        footer
        ;;
    5)
        echo "10 0 */7 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        header
        echo " Autoreboot has been set once a week."
        footer
        ;;
    6)
        echo "10 0 1 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        header
        echo " Autoreboot has been set once a month."
        footer
        ;;
    7)
        rm -f /etc/cron.d/reboot_otomatis
        header
        echo " Autoreboot has been disabled."
        footer
        ;;
    8)
        clear
        if [ -e /root/log-reboot.txt ]; then
            header
            cat /root/log-reboot.txt
            footer
        else
            header
            echo " No reboot activity found."
            footer
        fi
        ;;
    9)
        echo "" > /root/log-reboot.txt
        header
        echo " Autoreboot Log successfully deleted!"
        footer
        ;;
    x | X)
        clear
        m-setting
        ;;
    *)
        echo "Invalid option, please try again."
        ;;
esac