#!/bin/bash
clear
IP=$(wget -qO- ipinfo.io/ip)
date=$(date +"%Y-%m-%d")
Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Font_color_suffix="\033[0m"
Info="Online"
Error="Offline"
cek=$(crontab -l 2>/dev/null | grep -c "/usr/local/sbin/bckup-ku")

if [[ "$cek" = "1" ]]; then
    sts="${Info}"
else
    sts="${Error}"
fi

function start() {
    
    if [[ "$cek" = "0" ]]; then
        (crontab -l 2>/dev/null; echo "0 */5 * * * /usr/local/sbin/bckup-ku") | crontab -
        clear
        echo "======================================"
        echo " ❖ Autobackup Data"
        echo "--------------------------------------"
        echo -e " Autobackup has been started"
        echo -e " Data will be backed up automatically every 5 hours (GMT +7)"
        echo "======================================"
        sleep 3
    else
        clear
        echo "======================================"
        echo " ❖ Autobackup Data"
        echo "--------------------------------------"
        echo " Autobackup is activated"
        echo "======================================"
        
    fi
    sleep 1
    autobackup
}

function stop() {
    
    if [[ "$cek" = "1" ]]; then
        crontab -l 2>/dev/null | grep -v "/usr/local/sbin/bckup-ku" | crontab -
        echo -e "${RED}Autobackup Sudah di hentikan.${NC}"
    else
        echo -e "${ORANGE}Autobackup sudah tidak aktif.${NC}"
    fi
    sleep 1
    autobackup
}

setupbot() {
    clear
    echo "======================================"
    echo " ❖ Autobackup Bot Setup"
    echo "--------------------------------------"
    switch=$(grep -i "switch" /root/.bckupbot | awk '{print $2}' 2>/dev/null)
    read -p " Bot Token : " getToken
    read -p " Admin ID  : " adminID
    echo "$getToken" >/root/.bckupbot
    echo "$adminID" >>/root/.bckupbot
    echo "switch $switch" >>/root/.bckupbot
    echo
    echo -e "Bot Settings Successfully Saved"
    read -n 1 -s -r -p "Press any key to back"
    autobackup
}

clear
echo "======================================"
echo " ❖ Autobackup Data"
echo "--------------------------------------"
echo " + Status Autobackup : $sts"
echo "--------------------------------------"
echo " 1.  Start Autobackup"
echo " 2.  Stop Autobackup"
echo " 3.  Setup Bot Notification"
echo " x.  Exit"
echo "--------------------------------------"
echo " Note: Set Bot Notificaion First"
echo "======================================"
echo 
read -rp "Enter your option [1-3 or x] : " opt
case $opt in
1) clear ; start ;;
2) clear ; stop ;;
3) clear ; setupbot ;;
0) clear ; menu ; exit ;;
x) m-backup ;;
*) echo "You pressed it wrong!" ; sleep 1 ; autobackup ;;
esac