#!/bin/bash
clear

get_logged_in_users() {
    if [ -e "/var/log/auth.log" ]; then
        LOG="/var/log/auth.log"
    elif [ -e "/var/log/secure" ]; then
        LOG="/var/log/secure"
    else
        echo "Error: Could not find auth.log or secure log." >&2
        exit 1
    fi

    cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.txt
    data=( `ps aux | grep -i dropbear | awk '{print $2}'` )

    for PID in "${data[@]}"; do
        grep "dropbear\[$PID\]" /tmp/login-db.txt > /tmp/login-db-pid.txt
        NUM=$(cat /tmp/login-db-pid.txt | wc -l)
        
        if [ "$NUM" -eq 1 ]; then
            USER=$(awk -F"for '" '{print $2}' /tmp/login-db-pid.txt | awk '{print $1}')
            IP=$(awk -F"for '" '{print $2}' /tmp/login-db-pid.txt | awk '{print $4}' | sed "s/'$//")
            echo "$USER"
        fi
    done

    cat $LOG | grep -i sshd | grep -i "Accepted password for" > /tmp/login-db.txt
    data=( `ps aux | grep "sshd: " | grep -v "grep" | awk '{print $2}'` )

    for PID in "${data[@]}"; do
        grep "sshd\[$PID\]" /tmp/login-db.txt > /tmp/login-db-pid.txt
        NUM=$(cat /tmp/login-db-pid.txt | wc -l)

        if [ "$NUM" -eq 1 ]; then
            USER=$(awk -F"for " '{print $2}' /tmp/login-db-pid.txt | awk '{print $1}')
            IP=$(awk -F"from " '{print $2}' /tmp/login-db-pid.txt | awk '{print $1}')
            echo "$USER"
        fi
    done
}
clear

data1=( `awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd` )
for user in "${data1[@]}"; do
    dir="/etc/limit/ssh/ip"
    iplimit1="$dir/$user"

    if [[ ! -d $dir ]]; then
        mkdir -p $dir
    fi

    if [[ ! -f $iplimit1 || ! -s $iplimit1 ]]; then
        echo "2" > "$iplimit1"
    fi
done

clear
echo "======================================"
echo " ❖ SSH Account Login"
echo "--------------------------------------"
echo " Login IP     Limit IP     Username"
echo "--------------------------------------"

mulog=$(get_logged_in_users)
touch /root/.system

data=( `awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd` )

for user in "${data[@]}"; do
    # Count how many times the user appears in the login list
    cekcek=$(echo "$mulog" | grep -wE "$user" | wc -l)
    
    # [cite_start]If the user is logged in, display their info [cite: 27]
    if [[ $cekcek -gt 0 ]]; then
        iplimit=$(cat "/etc/limit/ssh/ip/$user")
        printf "  %-13s %-7s %-8s %2s\n" "     ${cekcek} IP        ${iplimit} IP      ${user}"
        # Keep track of active users
        echo "slot" >> /root/.system
    fi
done

aktif=$(cat /root/.system | wc -l)
echo "--------------------------------------"
echo " Account online: $aktif "
echo "======================================"

rm -f /root/.system
echo
read -n 1 -s -r -p "Press any key to back"
m-ssh