#!/bin/bash

clear
greenBe="\033[5;32m"
dateFromServer=$(curl -sI --insecure https://google.com/ | grep -i '^date:' | sed -e 's/Date: //')
biji=$(date +"%Y-%m-%d" -d "$dateFromServer")

fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "\033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 15; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}

echo -e "\e[91;1mDelete Bot\e[0m"
sleep 2
fun_bar
systemctl stop give
rm -rf /root/give.sh

cd /usr/bin || exit
rm -rf give give2 give3 give4 give5 give.zip give.zip.1 give.zip.2 give.zip.3 give.zip.4 give.zip.5 give2.zip give2.zip.1 give2.zip.2 give2.zip.3 give3.zip give3.zip.1 give3.zip.2 give3.zip.3 bot bot2 bot3 bot4 bot5 bot.zip bot.zip.1 bot.zip.2 bot.zip.3 bot.zip.4 bot.zip.5 bot-backup bot-cek-login-ssh bot-cek-ss \
       bot-cek-tr bot-cek-vless bot-cek-ws bot-member-ssh setting.py \
       bot-restore bot-vps-info
       sleep 1

echo -e "Successfully Delete Bot Give"
sleep 1
read -n 1 -s -r -p "Press any key to back"
m-give