#!/bin/bash
clear
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
hariini=$(date +%d-%m-%Y)
echo "======================================"
echo " Thank you for removing exp account"
echo "--------------------------------------"
cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
totalaccounts=$(cat /tmp/expirelist.txt | wc -l)

for ((i = 1; i <= $totalaccounts; i++)); do
    tuserval=$(sed -n "${i}p" /tmp/expirelist.txt)
    username=$(echo $tuserval | cut -f1 -d:)
    userexp=$(echo $tuserval | cut -f2 -d:)
    userexpireinseconds=$((userexp * 86400))
    tglexp=$(date -d @$userexpireinseconds)
    tgl=$(echo $tglexp | awk -F" " '{print $3}')

    while [ ${#tgl} -lt 2 ]; do
        tgl="0$tgl"
    done

    while [ ${#username} -lt 15 ]; do
        username="${username} "
    done

    bulantahun=$(echo $tglexp | awk -F" " '{print $2, $6}')
    echo -e "Expired- User: $username Expire at: $tgl $bulantahun" >> /usr/local/bin/alluser
    todaystime=$(date +%s)

    if [ $userexpireinseconds -ge $todaystime ]; then
        :
    else
        echo -e "Expired- Username: $username are expired at: $tgl $bulantahun and removed: $hariini" >> /usr/local/bin/deleteduser
        echo -e "Username $username that expired on $tgl $bulantahun removed from the VPS on $hariini"
        userdel $username
    fi
done
echo " Script has successfully run"
echo "======================================"
echo
read -n 1 -s -r -p "Press any key to back"
m-ssh