#!/bin/bash
clear
echo "======================================"
echo " ❖ Delete SSH Account"
echo "--------------------------------------"
echo " Username         Exp Date"
echo "--------------------------------------"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     "
else
printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     "
fi
fi
done < /etc/passwd
echo "======================================"
echo
read -p "Enter Username : " Pengguna

if getent passwd $Pengguna > /dev/null 2>&1; then
        userdel $Pengguna > /dev/null 2>&1
        clear
        echo "======================================"
        echo " ❖ Delete SSH Account"
        echo "--------------------------------------"
        echo " User $Pengguna deleted successfully"
        echo "======================================"
        echo
        read -n 1 -s -r -p "Press any key to back"
        m-ssh
else
        clear
        echo "======================================"
        echo " ❖ Delete SSH Account"
        echo "--------------------------------------"
        echo " User $Pengguna not found"
        echo "======================================"
        echo
        read -n 1 -s -r -p "Press any key to back"
        m-ssh
fi

