#!/bin/bash
clear

NUMBER_OF_CLIENTS=$(grep -c -E "^#& " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    clear
        echo "======================================"
        echo " ❖ Delete Vless Account"
        echo "--------------------------------------"
		echo " You have no existing clients!"
		echo "======================================"
        echo
		read -n 1 -s -r -p "Press any key to back"
        m-vless
	fi

clear
echo "======================================"
echo " ❖ Delete Vless Account"
echo "--------------------------------------"
printf " %-20s %s\n" "Username" "Exp Date"
echo "--------------------------------------"
grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq | while read -r user exp; do
    printf " %-20s %s\n" "$user" "$exp"
done
echo "======================================"
echo
read -rp "Enter Username : " user

if [ -z $user ]; then
    m-vless
else
    exp=$(grep -wE "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/^#& $user $exp/,/^},{/d" /etc/vless/.vless.db
    rm -rf /etc/vless/$user
    rm -rf /etc/limit/vless/ip/$user
    systemctl restart xray > /dev/null 2>&1
    clear
    echo "======================================"
    echo " ❖ Delete Vless Account"
    echo "--------------------------------------"
    echo " Username : $user"
    echo " Expired  : $exp"
    echo "======================================"
    echo
    read -n 1 -s -r -p "Press any key to back"
    m-vless
fi