#!/bin/bash
clear
source /usr/local/sbin/nuclear
echo "======================================"
echo " ❖ Fix Nginx & Haproxy Offline"
echo "--------------------------------------"
read -p " Input Your Domain : " domain
echo -e " Loading..."
sleep 2
rm -fr /etc/xray/domain
echo "${domain}" > /etc/xray/domain
systemctl stop nginx
wget -O /etc/nginx/conf.d/xray.conf "${REPO}xray.conf" >/dev/null 2>&1
curl -s "${REPO}nginx.conf" > /etc/nginx/nginx.conf
sed -i "s/xxx/${domain}/g" /etc/nginx/conf.d/xray.conf
systemctl restart nginx
install-haproxy
echo
echo -e "Configuration updated and services restarted successfully."
echo 
read -n 1 -s -r -p "Press any key to back"
m-setting