#!/bin/bash
clear
MYIP=$(wget -qO- ipinfo.io/ip);
echo "============================================"
echo " ❖ SSH Account List"
echo "--------------------------------------------"
echo " Username         Exp Date         Status "
echo "--------------------------------------------"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
    if [[ "$status" = "L" ]]; then
        printf " %-17s %2s %-17s %2s \n" "$AKUN" "$exp   " "LOCKED${NORMAL}"
    else
        printf " %-17s %2s %-17s %2s \n" "$AKUN" "$exp   " "UNLOCKED${NORMAL}"
    fi
fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo "--------------------------------------------"
echo " Total account: $JUMLAH user"
echo "============================================"
echo 
read -n 1 -s -r -p "Press any key to back"
m-ssh