#!/bin/bash
clear
echo "======================================"
echo " ❖ Shadowsocks Account List"
echo "--------------------------------------"
printf " %-20s %s\n" "Username" "Exp Date"
echo "--------------------------------------"
grep -E "^#@& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq | while read -r user exp; do
    printf " %-20s %s\n" "$user" "$exp"
done 
echo "======================================"
echo
read -n 1 -s -r -p "Press any key to back"
m-shadowsocks