#!/bin/bash
clear
source /usr/local/sbin/nuclear

PERMISSION() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    TODAY_DATE=$(date +'%Y-%m-%d')
    AUTHORIZED_ENTRY=$(curl -sS ${LICENSE} | grep -w "$MYIP" | head -1)

    if [[ -n "$AUTHORIZED_ENTRY" ]]; then
        IP_FROM_ENTRY=$(echo "$AUTHORIZED_ENTRY" | awk '{print $4}')
        EXP_DATE_OR_LIFETIME_STATUS=$(echo "$AUTHORIZED_ENTRY" | awk '{print $3}') 

        if [ "$MYIP" = "$IP_FROM_ENTRY" ]; then
            if [[ "$EXP_DATE_OR_LIFETIME_STATUS" == "lifetime" ]]; then
                echo -e "\033[1;92mPermission Accepted (Lifetime User)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Pengguna Lifetime)${NC}"
            elif [[ "$TODAY_DATE" < "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;92mPermission Accepted\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan${NC}"
            elif [[ "$TODAY_DATE" == "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;93mPermission Accepted (Today is Expiry Date)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Hari Ini Kadaluarsa)${NC}"
            else
                echo -e "\033[1;91mPermission Denied (Expired)\033[0m"
                echo -e "\033[1;97mAkses Di Tolak (Kadaluarsa)${NC}"
                read -n 1 -s -r -p "Press [ Enter ] to Exit"
                exit 1
            fi
        else
            echo -e "\033[1;91mPermission Denied (IP Mismatch)\033[0m"
            echo -e "\033[1;97mAkses Di Tolak (IP Tidak Cocok)${NC}"
            read -n 1 -s -r -p "Press [ Enter ] to Exit"
            exit 1
        fi
    else
        echo -e "\033[1;91mPermission Denied (IP Not Found)\033[0m"
        echo -e "\033[1;97mAkses Di Tolak (IP Tidak Ditemukan)${NC}"
        read -n 1 -s -r -p "Press [ Enter ] to Exit"
        exit 1
    fi
}

PERMISSION
clear

DROPBEAR_BIN="/usr/sbin/dropbear"
DROPBEAR_LIB="/usr/lib/dropbear"
DROPBEAR_CONFIG="/etc/dropbear"
DROPBEAR_MAN="/usr/share/man/man8/dropbear.8.gz"
DROPBEAR_URL="https://matt.ucc.asn.au/dropbear/releases"
clear

echo "======================================"
echo " ❖ Change Dropbear Version"
echo "--------------------------------------"
echo " 1.  Dropbear Ver 2018"
echo " 2.  Dropbear Ver 2019"
echo " 3.  Dropbear Ver 2020"
echo " 4.  Dropbear Ver 2022"
echo " 5.  Dropbear Ver 2024"
echo " x.  Exit"
echo "======================================"
echo
read -p "Enter your option [1-5 or x] : " opt
case $opt in
1) clear ; DROPBEAR_VERSION="2018.76" ;;
2) clear ; DROPBEAR_VERSION="2019.78" ;;
3) clear ; DROPBEAR_VERSION="2020.81" ;;
4) clear ; DROPBEAR_VERSION="2022.82" ;;
5) clear ; DROPBEAR_VERSION="2024.86" ;;
x) clear ; m-setting ;;
*) echo "You pressed it wrong!" ; sleep 1 ; m-dropbear ;;
esac

clear
echo "======================================"
echo " ❖ Installing Dropbear Version"
echo "--------------------------------------"

if systemctl stop dropbear || service dropbear stop; then
    echo " Dropbear stoped"
else
    echo " Failed to stop Dropbear"
fi

clear
if [ -f "$DROPBEAR_BIN" ]; then
    echo " Backup old version of Dropbear..."
    cp $DROPBEAR_BIN /usr/sbin/dropbear.bak
fi

rm -f $DROPBEAR_BIN $DROPBEAR_LIB/* $DROPBEAR_CONFIG/* $DROPBEAR_MAN
clear

apt-get update && apt-get install -y build-essential zlib1g-dev wget || yum groupinstall "Development Tools" -y && yum install zlib-devel wget -y
clear

echo -e " Downloading dropbear version $DROPBEAR_VERSION..."
wget --no-check-certificate -O dropbear.tar.bz2 "$DROPBEAR_URL/dropbear-$DROPBEAR_VERSION.tar.bz2"

if [ ! -f "dropbear.tar.bz2" ]; then
    echo -e " Download failed, check URL or internet connection"
    read -n 1 -s -r -p "Press any key to back"
    m-dropbear
fi

tar -xjf dropbear.tar.bz2
cd "dropbear-$DROPBEAR_VERSION" || exit

clear
if ./configure --prefix=/usr && make && make install; then
    echo -e "Compilation successful"
else
    echo -e "Compilation failed"
    read -n 1 -s -r -p "Press any key to back"
    m-dropbear
fi

clear
mv /usr/bin/dropbear $DROPBEAR_BIN
mkdir -p $DROPBEAR_LIB
mkdir -p $DROPBEAR_CONFIG
if [ -f "/usr/share/man/man8/dropbear.8.gz" ]; then
    mv /usr/share/man/man8/dropbear.8.gz $DROPBEAR_MAN
else
    echo -e "File man not found"
fi

clear
rm -f /etc/dropbear/dropbear_rsa_host_key
rm -f /etc/dropbear/dropbear_dss_host_key
rm -f /etc/dropbear/dropbear_ecdsa_host_key

dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key

chmod 600 /etc/dropbear/dropbear_rsa_host_key
chmod 600 /etc/dropbear/dropbear_dss_host_key
chmod 600 /etc/dropbear/dropbear_ecdsa_host_key

clear
if systemctl start dropbear || service dropbear start; then
    echo -e "Dropbear started successfully"
else
    echo -e "Failed to start Dropbear"
fi

clear
if dropbear -V; then
    echo -e "Dropbear version $DROPBEAR_VERSION has been installed"
else
    echo -e "Verification failed, dropbear may not be installed correctly"
fi
clear

cd ..
rm -rf dropbear.tar.bz2 "dropbear-$DROPBEAR_VERSION"
echo "--------------------------------------"
echo " Dropbear version $DROPBEAR_VERSION installed successfully!"
echo "======================================"
echo
read -n 1 -s -r -p "Press any key to back"
m-dropbear
