#!/bin/bash
clear
source /usr/local/sbin/nuclear

PERMISSION() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    TODAY_DATE=$(date +'%Y-%m-%d')
    AUTHORIZED_ENTRY=$(curl -sS ${LICENSE} | grep -w "$MYIP" | head -1)

    if [[ -n "$AUTHORIZED_ENTRY" ]]; then
        IP_FROM_ENTRY=$(echo "$AUTHORIZED_ENTRY" | awk '{print $4}')
        EXP_DATE_OR_LIFETIME_STATUS=$(echo "$AUTHORIZED_ENTRY" | awk '{print $3}') 

        if [ "$MYIP" = "$IP_FROM_ENTRY" ]; then
            if [[ "$EXP_DATE_OR_LIFETIME_STATUS" == "lifetime" ]]; then
                echo -e "\033[1;92mPermission Accepted (Lifetime User)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Pengguna Lifetime)${NC}"
            elif [[ "$TODAY_DATE" < "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;92mPermission Accepted\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan${NC}"
            elif [[ "$TODAY_DATE" == "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;93mPermission Accepted (Today is Expiry Date)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Hari Ini Kadaluarsa)${NC}"
            else
                echo -e "\033[1;91mPermission Denied (Expired)\033[0m"
                echo -e "\033[1;97mAkses Di Tolak (Kadaluarsa)${NC}"
                read -n 1 -s -r -p "Press [ Enter ] to Exit"
                exit 1
            fi
        else
            echo -e "\033[1;91mPermission Denied (IP Mismatch)\033[0m"
            echo -e "\033[1;97mAkses Di Tolak (IP Tidak Cocok)${NC}"
            read -n 1 -s -r -p "Press [ Enter ] to Exit"
            exit 1
        fi
    else
        echo -e "\033[1;91mPermission Denied (IP Not Found)\033[0m"
        echo -e "\033[1;97mAkses Di Tolak (IP Tidak Ditemukan)${NC}"
        read -n 1 -s -r -p "Press [ Enter ] to Exit"
        exit 1
    fi
}

#PERMISSION
clear
function manage_systemd_limit_service() {
    local LIMIT_IP_SERVICES=(
        "limiter-vm"
        "limiter-vl"
        "limiter-trj"
        "limiter-shd"
        "limiter-ssh"
    )
    local LIMIT_QUOTA_SERVICES=(
        "limitvmess"
        "limitvless"
        "limittrojan"
        "limitshadowsocks"
    )

    get_status_group() {
        local services=("${@}")
        local all_on=true
        for svc in "${services[@]}"; do
            if ! systemctl is-enabled --quiet "${svc}.timer" || ! systemctl is-active --quiet "${svc}.timer"; then
                all_on=false
                break
            fi
        done
        if "$all_on"; then
            echo -e "Online"
        else
            echo -e "Offline"
        fi
    }

    enable_services() {
        for svc in "${@}"; do
            echo "Activate ${svc}.timer..."
            if systemctl enable --now --quiet "${svc}.timer"; then
                echo -e "${svc}.the timer has been successfully activated"
            else
                echo -e "Failed to activate ${svc}.timer"
            fi
        done
    }

    disable_services() {
        for svc in "${@}"; do
            echo "Disable ${svc}.timer..."
            if systemctl disable --now --quiet "${svc}.timer"; then
                echo -e "${svc}.the timer has been successfully turned off"
            else
                echo -e "Failed to deactivate ${svc}.timer"
            fi
        done
    }

    while true; do
        local status_cron_quota=$(get_status_group "${LIMIT_QUOTA_SERVICES[@]}")
        local status_cron_ip=$(get_status_group "${LIMIT_IP_SERVICES[@]}")
        clear
        echo "======================================"
        echo " ❖ IP & Quota Limit Service"
        echo "--------------------------------------"
        echo " + Service Status"
        echo " Quota Limit : $status_cron_quota"
        echo " IP Limit    : $status_cron_ip"
        echo "--------------------------------------"
        echo " 1.  Enable Service Quota Limit"
        echo " 2.  Disable Service Quota Limit"
        echo " 3.  Enable Service IP Limit"
        echo " 4.  Disable Service IP Limit"
        echo " x.  Exit"
        echo "======================================"
        echo
        read -p "Enter your option [1-4 or x] : " opt

        case "$opt" in
            1|01) enable_services "${LIMIT_QUOTA_SERVICES[@]}" ;;
            2|02) disable_services "${LIMIT_QUOTA_SERVICES[@]}" ;;
            3|03) enable_services "${LIMIT_IP_SERVICES[@]}" ;;
            4|04) disable_services "${LIMIT_IP_SERVICES[@]}" ;;
            x) clear ; m-setting ;;
            *) echo "You pressed it wrong!" ; sleep 1 ; m-mulog ;;
        esac
    done
}

manage_systemd_limit_service