#!/bin/bash
clear
source /usr/local/sbin/nuclear

PERMISSION() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    TODAY_DATE=$(date +'%Y-%m-%d')
    AUTHORIZED_ENTRY=$(curl -sS ${LICENSE} | grep -w "$MYIP" | head -1)

    if [[ -n "$AUTHORIZED_ENTRY" ]]; then
        IP_FROM_ENTRY=$(echo "$AUTHORIZED_ENTRY" | awk '{print $4}')
        EXP_DATE_OR_LIFETIME_STATUS=$(echo "$AUTHORIZED_ENTRY" | awk '{print $3}') 

        if [ "$MYIP" = "$IP_FROM_ENTRY" ]; then
            if [[ "$EXP_DATE_OR_LIFETIME_STATUS" == "lifetime" ]]; then
                echo -e "\033[1;92mPermission Accepted (Lifetime User)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Pengguna Lifetime)${NC}"
            elif [[ "$TODAY_DATE" < "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;92mPermission Accepted\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan${NC}"
            elif [[ "$TODAY_DATE" == "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;93mPermission Accepted (Today is Expiry Date)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Hari Ini Kadaluarsa)${NC}"
            else
                echo -e "\033[1;91mPermission Denied (Expired)\033[0m"
                echo -e "\033[1;97mAkses Di Tolak (Kadaluarsa)${NC}"
                read -n 1 -s -r -p "Press [ Enter ] to Exit"
                exit 1
            fi
        else
            echo -e "\033[1;91mPermission Denied (IP Mismatch)\033[0m"
            echo -e "\033[1;97mAkses Di Tolak (IP Tidak Cocok)${NC}"
            read -n 1 -s -r -p "Press [ Enter ] to Exit"
            exit 1
        fi
    else
        echo -e "\033[1;91mPermission Denied (IP Not Found)\033[0m"
        echo -e "\033[1;97mAkses Di Tolak (IP Tidak Ditemukan)${NC}"
        read -n 1 -s -r -p "Press [ Enter ] to Exit"
        exit 1
    fi
}
PERMISSION

tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"

clear
function ins_noobz() {
  clear
  echo -e "${runn} Installing NoobzVPN...${Suffix}"
  wget ${REPO}noobzvpns.zip
  unzip noobzvpns.zip
  rm -rf noobzvpns.zip noobzvpns.zip.1 noobzvpns.zip.2 noobzvpns.zip.3 noobzvpns.zip.4
  cd noobzvpns
  chmod +x install.sh
  ./install.sh
  systemctl start noobzvpns
  systemctl restart noobzvpns
  echo -e "NoobzVPN successfully installed!"
  read -n 1 -s -r -p "Press any key to back"
  m-nob
}

function uninstall_noobz() {
  clear
  echo -e "Uninstalling NoobzVPN"
  systemctl stop noobzvpns
  systemctl disable noobzvpns
  rm -rf /etc/noobzvpns
  rm -rf /usr/local/bin/noobzvpns
  rm -f /etc/systemd/system/noobzvpns.service
  echo -e "NoobzVPN successfully uninstalled!"
  read -n 1 -s -r -p "Press any key to back"
  m-nob

}

function restart_noobz() {
  clear
  echo -e "Restarting NoobzVPN"
  systemctl restart noobzvpns
  echo -e "NoobzVPN successfully restarted!"
  read -n 1 -s -r -p "Press any key to back"
  m-nob
}

function add_noobvpn_user() {
  clear
  echo "======================================"
  echo " ❖ Create Noobz VPN Account"
  echo "--------------------------------------"
  echo " Input username [ex: dudul69]"
  echo " Limit IP [ex: 10] for 10 devices"
  echo " Limit Quota [ex: 1000] for 1 TB"
  echo "--------------------------------------"
  read -p " Username    : " username
  read -p " Password    : " pass
  read -p " Expired     : " masaaktif
  read -p " Limit IP    : " ip
  read -p " Limit Quota : " Quota

  if [[ -z "$masaaktif" || "$masaaktif" =~ [^0-9] ]]; then
    echo "Invalid expiration input. Please input a valid number of days."
    exit 1
  fi

  if [[ "$masaaktif" -eq 0 ]]; then
    expe="Unlimited"
  else
    tgl=$(date -d "$masaaktif days" +"%d")
    bln=$(date -d "$masaaktif days" +"%b")
    thn=$(date -d "$masaaktif days" +"%Y")
    expe="$tgl $bln, $thn"
  fi

  if noobzvpns --add-user "$username" "$pass" --expired-user "$username" "$expe"; then
    echo "Account $username successfully created!"
  else
    echo "Failed to create account $username."
    exit 1
  fi

  mkdir -p /etc/limit/noobzvpns/ip/
  echo "$ip" > "/etc/limit/noobzvpns/ip/$username"

  Quota=${Quota:-0}
  c=$(echo "$Quota" | sed 's/[^0-9]//g')
  if [[ "$c" -gt 0 ]]; then
    d=$((c * 1024 * 1024 * 1024))
    echo "$d" > "/etc/noobzvpns/$username"
  fi

  mkdir -p /etc/noobzvpns/
  touch /etc/noobzvpns/.noobzvpns.db
  sed -i "/\b$username\b/d" /etc/noobzvpns/.noobzvpns.db
  echo "#nob# $username $pass $ip $Quota $expe" >> "/etc/noobzvpns/.noobzvpns.db"

  mkdir -p /detail/nob/
  cat > /detail/nob/$username.txt <<-END
=========
❖ Noobz VPN Account
=========
Host         : $(cat /etc/xray/domain)
Username     : $username
Password     : $pass
Port Non TLS : 2082
Port TLS     : 2083
Limit IP     : $ip IP
Limit Quota  : $Quota GB
=========
Create at    : $tnggl
Expired      : $expe
=========
END

  if [ -f "/etc/bot/.bot.db" ]; then
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    export TIME="10"
    export URL="https://api.telegram.org/bot$KEY/sendMessage"

    # Sensor username (3 huruf pertama saja)
    sensor=$(echo "$username" | cut -c1-3)xxx
    domain=$(cat /etc/xray/domain)
    ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10)

    TEXT="
<b>=========</b>
<b>❖ TRANSACTION SUCCESSFULL  </b>
<b>=========</b>
<b>Product     :</b> Noobz VPN
<b>ISP         :</b> <code>${ISP}</code>
<b>Limit Quota :</b> <code>${Quota} GB</code>
<b>Limit Login :</b> <code>${iplimit} IP</code>
<b>Username    :</b> <code>${sensor}</code>
<b>Duration    :</b> <code>${masaaktif} Days</code>
<b>=========</b>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" "$URL" >/dev/null
else
echo
  fi
  clear
  echo "========="
  echo "❖ Noobz VPN Account"
  echo "========="
  echo "Host         : $(cat /etc/xray/domain)"
  echo "Username     : $username"
  echo "Password     : $pass"
  echo "Port Non TLS : 2082"
  echo "Port TLS     : 2083"
  echo "Limit IP     : $ip IP"
  echo "Limit Quota  : $Quota GB"
  echo "========="
  echo "Create at    : $tnggl"
  echo "Expired      : $expe"
  echo "========="
  echo
  read -n 1 -s -r -p "Press any key to back"
  m-nob
}

function block_user() {
    echo "======================================"
    echo " ❖ Lock Noobz VPN Account"
    echo "--------------------------------------"
    echo
    read -p "Enter username to block: " username
    noobzvpns --block-user "$username"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

function unblock_user() {
    echo "======================================"
    echo " ❖ Unlock Noobz VPN Account"
    echo "--------------------------------------"
    echo
    read -p "Enter username to unblock: " username
    noobzvpns --unblock-user "$username"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

function set_expiration() {
    echo "======================================"
    echo " ❖ Set Expired Noobz VPN Account"
    echo "--------------------------------------"
    echo
    read -p "Enter username : " username
    read -p "Enter Expired  : " days
    noobzvpns --expired-user "$username" "$days"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

function renew_expiration() {
    echo "======================================"
    echo " ❖ Renew Noobz VPN Account"
    echo "--------------------------------------"
    echo
    read -p "Enter username : " username
    noobzvpns --renew-user "$username"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

function change_password() {
    echo "======================================"
    echo " ❖ Change Password Noobz VPN Account"
    echo "--------------------------------------"
    echo
    read -p "Enter username     : " username
    read -p "Enter new password : " new_password
    noobzvpns --password-user "$username" "$new_password"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

function rename_user() {
    echo "======================================"
    echo " ❖ Rename Noobz VPN Account"
    echo "--------------------------------------"
    echo
    read -p "Enter current username : " old_username
    read -p "Enter new username     : " new_username
    noobzvpns --rename-user "$old_username" "$new_username"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

function remove_user() {
    echo "======================================"
    echo " ❖ Delete Noobz VPN Account"
    echo "--------------------------------------"
    echo
    read -p "Enter username : " username
    noobzvpns --remove-user "$username"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

function remove_all_users() {
    echo "======================================"
    echo " ❖ Remove All Noobz VPN Account"
    echo "--------------------------------------"
    echo
    read -p "Are you sure you want to remove all users? (yes/no): " confirm
    if [ "$confirm" == "yes" ]; then
        noobzvpns --remove-all-user
    else
        echo "Operation cancelled."
    fi
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

function info_user() {
    echo "======================================"
    echo " ❖ Detail Noobz VPN Account"
    echo "--------------------------------------"
    echo
    read -p "Enter username : " username
    noobzvpns --info-user "$username"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

function info_all_users() {
    echo "======================================"
    echo " ❖ Detail All Noobz VPN Account"
    echo "--------------------------------------"
    echo
    noobzvpns --info-all-user
    read -n 1 -s -r -p "Press any key to back"
    m-nob
}

clear
echo "======================================"
echo " ❖ Noobz VPN Menu"
echo "--------------------------------------"
echo " 1.  Install Service"
echo " 2.  Uninstall Service"
echo " 3.  Restart Service"
echo " 4.  Create Account"
echo " 5.  Lock Account"
echo " 6.  Unlock Account"
echo " 7.  Set Expiretion"
echo " 8.  Renew Account"
echo " 9.  Change Password Account"
echo " 10. Rename User"
echo " 11. Delete Account"
echo " 12. Remove All Account"
echo " 13. Information Account"
echo " 14. Information All Account"
echo " 15. Detail Account"
echo " x.  Exit"
echo "======================================"
echo 
read -p "Enter your option [1-15 or x] : " opt
case $opt in
1) clear ; ins_noobz ;;
2) clear ; uninstall_noobz ;;
3) clear ; restart_noobz ;;
4) clear ; add_noobvpn_user ;;
5) clear ; block_user ;;
6) clear ; unblock_user ;;
7) clear ; set_expiration ;;
8) clear ; renew_expiration ;;
9) clear ; change_password ;;
10) clear ; rename_user ;;
11) clear ; remove_user ;;
12) clear ; remove_all_users ;;
13) clear ; info_user ;;
14) clear ; info_all_users ;;
15) clear ; usernob ;;
x) menu ;;
*) echo "You pressed it wrong!" ; sleep 1 ; m-nob ;;
esac