#!/bin/bash
clear
source /usr/local/sbin/nuclear

PERMISSION() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    TODAY_DATE=$(date +'%Y-%m-%d')
    AUTHORIZED_ENTRY=$(curl -sS ${LICENSE} | grep -w "$MYIP" | head -1)

    if [[ -n "$AUTHORIZED_ENTRY" ]]; then
        IP_FROM_ENTRY=$(echo "$AUTHORIZED_ENTRY" | awk '{print $4}')
        EXP_DATE_OR_LIFETIME_STATUS=$(echo "$AUTHORIZED_ENTRY" | awk '{print $3}') 

        if [ "$MYIP" = "$IP_FROM_ENTRY" ]; then
            if [[ "$EXP_DATE_OR_LIFETIME_STATUS" == "lifetime" ]]; then
                echo -e "\033[1;92mPermission Accepted (Lifetime User)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Pengguna Lifetime)${NC}"
            elif [[ "$TODAY_DATE" < "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;92mPermission Accepted\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan${NC}"
            elif [[ "$TODAY_DATE" == "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;93mPermission Accepted (Today is Expiry Date)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Hari Ini Kadaluarsa)${NC}"
            else
                echo -e "\033[1;91mPermission Denied (Expired)\033[0m"
                echo -e "\033[1;97mAkses Di Tolak (Kadaluarsa)${NC}"
                read -n 1 -s -r -p "Press [ Enter ] to Exit"
                exit 1
            fi
        else
            echo -e "\033[1;91mPermission Denied (IP Mismatch)\033[0m"
            echo -e "\033[1;97mAkses Di Tolak (IP Tidak Cocok)${NC}"
            read -n 1 -s -r -p "Press [ Enter ] to Exit"
            exit 1
        fi
    else
        echo -e "\033[1;91mPermission Denied (IP Not Found)\033[0m"
        echo -e "\033[1;97mAkses Di Tolak (IP Tidak Ditemukan)${NC}"
        read -n 1 -s -r -p "Press [ Enter ] to Exit"
        exit 1
    fi
}
PERMISSION

clear
function osx_ubuntu() {
  echo "======================================"
  echo " ❖ Rebuild VPS Ubuntu"
  echo "--------------------------------------"
  echo " 1.  Ubuntu 20.04"
  echo " 2.  Ubuntu 22.04"
  echo " 3.  Ubuntu 24.04"
  echo " 4.  Ubuntu 24.10"
  echo " x.  Exit"
  echo "======================================"
  echo 
  read -p "Enter your option [1-4 or x] : " opt
  echo -e ""
case $opt in
1) clear ; ub20.04 ;;
2) clear ; ub22.04 ;;
3) clear ; ub24.04 ;;
4) clear ; ub24.10 ;;
x) clear ; m-rebuild ;;
*) echo "You pressed it wrong!" ; sleep 1 ; m-rebuild ;;
esac
}


function ub20.04() {
  curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh && bash reinstall.sh Ubuntu 20.04 && reboot
}

function ub22.04() {
  curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh && bash reinstall.sh Ubuntu 22.04 && reboot
}

function ub24.04() {
  curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh && bash reinstall.sh Ubuntu 24.04 && reboot
}

function ub24.10() {
  curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh && bash reinstall.sh Ubuntu 24.10 && reboot
}

function osx_debian() {
  echo "======================================"
  echo " ❖ Rebuild VPS Debian"
  echo "--------------------------------------"
  echo " 1.  Detail Account"
  echo " 2.  Change Limit IP"
  echo " 3.  Change Limit Quota"
  echo " x.  Exit"
  echo "======================================"
  echo
  read -p "Enter your option [1-3 or x] : " opt
  echo -e ""
case $opt in
1) clear ; deb10 ;;
2) clear ; deb11 ;;
3) clear ; deb12 ;;
x) clear ; m-rebuild ;;
*) echo "You pressed it wrong!" ; sleep 1 ; m-rebuild ;;
esac
}

function deb10() {
  curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh && bash reinstall.sh Debian 10 && reboot
}
function deb11() {
  curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh && bash reinstall.sh Debian 11 && reboot
}

function deb12() {
  curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh && bash reinstall.sh Debian 12 && reboot
}

echo "======================================"
echo " ❖ Rebuild VPS Menu"
echo "--------------------------------------"
echo " 1.  Rebuild VPS Debian"
echo " 2.  Rebuild VPS Ubuntu"
echo " x.  Exit"
echo "======================================"
echo
read -p "Enter your option [1-2 or x] : " Opt
case $Opt in
1) clear ; osx_debian ;;
2) clear ; osx_ubuntu ;;
x) clear ; m-setting ;;
*) echo "You pressed it wrong!" ; sleep 1 ; m-rebuild ;;
esac