#!/bin/bash
clear
source /usr/local/sbin/nuclear

PERMISSION() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    TODAY_DATE=$(date +'%Y-%m-%d')
    AUTHORIZED_ENTRY=$(curl -sS ${LICENSE} | grep -w "$MYIP" | head -1)

    if [[ -n "$AUTHORIZED_ENTRY" ]]; then
        IP_FROM_ENTRY=$(echo "$AUTHORIZED_ENTRY" | awk '{print $4}')
        EXP_DATE_OR_LIFETIME_STATUS=$(echo "$AUTHORIZED_ENTRY" | awk '{print $3}') 

        if [ "$MYIP" = "$IP_FROM_ENTRY" ]; then
            if [[ "$EXP_DATE_OR_LIFETIME_STATUS" == "lifetime" ]]; then
                echo -e "\033[1;92mPermission Accepted (Lifetime User)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Pengguna Lifetime)${NC}"
            elif [[ "$TODAY_DATE" < "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;92mPermission Accepted\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan${NC}"
            elif [[ "$TODAY_DATE" == "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;93mPermission Accepted (Today is Expiry Date)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Hari Ini Kadaluarsa)${NC}"
            else
                echo -e "\033[1;91mPermission Denied (Expired)\033[0m"
                echo -e "\033[1;97mAkses Di Tolak (Kadaluarsa)${NC}"
                read -n 1 -s -r -p "Press [ Enter ] to Exit"
                exit 1
            fi
        else
            echo -e "\033[1;91mPermission Denied (IP Mismatch)\033[0m"
            echo -e "\033[1;97mAkses Di Tolak (IP Tidak Cocok)${NC}"
            read -n 1 -s -r -p "Press [ Enter ] to Exit"
            exit 1
        fi
    else
        echo -e "\033[1;91mPermission Denied (IP Not Found)\033[0m"
        echo -e "\033[1;97mAkses Di Tolak (IP Tidak Ditemukan)${NC}"
        read -n 1 -s -r -p "Press [ Enter ] to Exit"
        exit 1
    fi
}

PERMISSION
clear
echo "======================================"
echo " ❖ Miscellaneous Menu"
echo "--------------------------------------"
echo " 1.  Change Xray UUID"
echo " 2.  Install UDP Custom"
echo " 3.  Setup Reboot Time"
echo " 4.  Setup Auto Reboot"
echo " 5.  Check Running Service"
echo " 6.  Setup Multilogin"
echo " 7.  Check RAM & CPU"
echo " 8.  Install ZiVPN"
echo " 9.  Service Port"
echo " 10. Rebuild VPS"
echo " 11. Trial Xray Menu"
echo " 12. Fix Nginx"
echo " 13. Bandwidth Monitor"
echo " 14. Change Dropbear"
echo " 15. Change Domain"
echo " 16. Change Banner"
echo " 17. Restart Service"
echo " 18. Warp Cloudflare"
echo " x.  Exit"
echo "======================================"
echo 
read -p "Enter your option [1-18 or x] : " opt
case $opt in
01|1) clear ; ganti-id ;;
02|2) clear ; install-udp ; read -p "Press enter Back To Menu" ; m-setting ;;
03|3) clear ; setupreboot ;;
04|4) clear ; autoreboot ;;
05|5) clear ; run ;;
06|6) clear ; m-mulog ;;
07|7) clear ; htop ; read -n 1 -s -r -p "Press any key to back" ; m-setting ;;
08|8) clear ; wget -q ${REPO}zivpn/install.sh && chmod +x install.sh && install.sh && rm -rf install.sh ;;
09|9) clear ; prot ;;
10) clear ; m-rebuild ;;
11) clear ; m-trial ;;
12) clear ; fix-nginx ;;
13) clear ; bw ;;
14) clear ; m-dropbear ; read -n 1 -s -r -p "Press any key to back" ; m-setting ;;
15) clear ; m-domain ;;
16) clear ; nano /etc/banner-ssh.txt ; read -n 1 -s -r -p "Press any key to back" ; m-setting ;;
17) clear ; restart ;;
17) clear ; m-warp ;;
x|x) clear ; menu ;;
*) echo "You pressed it wrong!" ; sleep 0.5 ; m-setting ;;
esac
