#!/bin/bash
clear
source /usr/local/sbin/nuclear

PERMISSION() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    TODAY_DATE=$(date +'%Y-%m-%d')
    AUTHORIZED_ENTRY=$(curl -sS ${LICENSE} | grep -w "$MYIP" | head -1)

    if [[ -n "$AUTHORIZED_ENTRY" ]]; then
        IP_FROM_ENTRY=$(echo "$AUTHORIZED_ENTRY" | awk '{print $4}')
        EXP_DATE_OR_LIFETIME_STATUS=$(echo "$AUTHORIZED_ENTRY" | awk '{print $3}') 

        if [ "$MYIP" = "$IP_FROM_ENTRY" ]; then
            if [[ "$EXP_DATE_OR_LIFETIME_STATUS" == "lifetime" ]]; then
                echo -e "\033[1;92mPermission Accepted (Lifetime User)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Pengguna Lifetime)${NC}"
            elif [[ "$TODAY_DATE" < "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;92mPermission Accepted\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan${NC}"
            elif [[ "$TODAY_DATE" == "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;93mPermission Accepted (Today is Expiry Date)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Hari Ini Kadaluarsa)${NC}"
            else
                echo -e "\033[1;91mPermission Denied (Expired)\033[0m"
                echo -e "\033[1;97mAkses Di Tolak (Kadaluarsa)${NC}"
                read -n 1 -s -r -p "Press [ Enter ] to Exit"
                exit 1
            fi
        else
            echo -e "\033[1;91mPermission Denied (IP Mismatch)\033[0m"
            echo -e "\033[1;97mAkses Di Tolak (IP Tidak Cocok)${NC}"
            read -n 1 -s -r -p "Press [ Enter ] to Exit"
            exit 1
        fi
    else
        echo -e "\033[1;91mPermission Denied (IP Not Found)\033[0m"
        echo -e "\033[1;97mAkses Di Tolak (IP Tidak Ditemukan)${NC}"
        read -n 1 -s -r -p "Press [ Enter ] to Exit"
        exit 1
    fi
}
PERMISSION

clear
remove_slowdns() {
    if systemctl is-active --quiet server-sldns; then
        systemctl stop server-sldns
        systemctl disable server-sldns
        read -n 1 -s -r -p "Press [ Enter ] to kembali ke menu"
        m-slowdns
    fi

    rm -rf /etc/slowdns
    rm /etc/systemd/system/server-sldns.service /etc/systemd/system/server-sldns.service

    systemctl daemon-reload

    echo -e "\033[32mSlowDNS Removed Successfully!\033[0m"
    read -n 1 -s -r -p "Press [ Enter ] to kembali ke menu"
    m-slowdns
}

restart_slowdns() {
    systemctl restart server-sldns
    echo -e "\033[32mSlowDNS Services Restarted Successfully!\033[0m"
    read -n 1 -s -r -p "Press [ Enter ] to kembali ke menu"
    m-slowdns
}

stop_slowdns() {
    systemctl stop server-sldns
    echo -e "\033[32mSlowDNS Services Stopped!\033[0m"
    read -n 1 -s -r -p "Press [ Enter ] to kembali ke menu"
    m-slowdns
}

clear
echo "======================================"
echo " ❖ Slow DNS Menu"
echo "--------------------------------------"
echo " 1.  Install Service"
echo " 2.  Delete Service"
echo " 3.  Restart Service"
echo " 4.  Stop Service"
echo " 5.  Status Service"
echo " x.  Exit"
echo "======================================"
echo
read -p "Enter your option [1-5 or x] : " opt
case $opt in
1) clear ; install-slowdns ;;
2) clear ; remove_slowdns ;;
3) clear ; restart_slowdns ;;
4) clear ; stop_slowdns ;;
5) clear ; systemctl status server-sldns.service ; read -n 1 -s -r -p "Press [ Enter ] to kembali ke menu" ; m-slowdns ;;
0) clear ; menu ; exit ;;
x) clear ; menu ;;
*) echo "You pressed it wrong!" ; sleep 1 ; m-slowdns ;;
esac