#!/bin/bash
clear
source /usr/local/sbin/nuclear

PERMISSION() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    TODAY_DATE=$(date +'%Y-%m-%d')
    AUTHORIZED_ENTRY=$(curl -sS ${LICENSE} | grep -w "$MYIP" | head -1)

    if [[ -n "$AUTHORIZED_ENTRY" ]]; then
        IP_FROM_ENTRY=$(echo "$AUTHORIZED_ENTRY" | awk '{print $4}')
        EXP_DATE_OR_LIFETIME_STATUS=$(echo "$AUTHORIZED_ENTRY" | awk '{print $3}') 

        if [ "$MYIP" = "$IP_FROM_ENTRY" ]; then
            if [[ "$EXP_DATE_OR_LIFETIME_STATUS" == "lifetime" ]]; then
                echo -e "\033[1;92mPermission Accepted (Lifetime User)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Pengguna Lifetime)${NC}"
            elif [[ "$TODAY_DATE" < "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;92mPermission Accepted\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan${NC}"
            elif [[ "$TODAY_DATE" == "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;93mPermission Accepted (Today is Expiry Date)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Hari Ini Kadaluarsa)${NC}"
            else
                echo -e "\033[1;91mPermission Denied (Expired)\033[0m"
                echo -e "\033[1;97mAkses Di Tolak (Kadaluarsa)${NC}"
                read -n 1 -s -r -p "Press [ Enter ] to Exit"
                exit 1
            fi
        else
            echo -e "\033[1;91mPermission Denied (IP Mismatch)\033[0m"
            echo -e "\033[1;97mAkses Di Tolak (IP Tidak Cocok)${NC}"
            read -n 1 -s -r -p "Press [ Enter ] to Exit"
            exit 1
        fi
    else
        echo -e "\033[1;91mPermission Denied (IP Not Found)\033[0m"
        echo -e "\033[1;97mAkses Di Tolak (IP Tidak Ditemukan)${NC}"
        read -n 1 -s -r -p "Press [ Enter ] to Exit"
        exit 1
    fi
}
PERMISSION

clear
echo "======================================"
echo " ❖ Xray Trojan Menu"
echo "--------------------------------------"
echo " 1.  Create Account"
echo " 2.  Create Trial Account"
echo " 3.  Renew Account"
echo " 4.  Delete Account"
echo " 5.  Check Login Account"
echo " 6.  List Account"
echo " 7.  List Locked Account"
echo " 8.  Lock Account"
echo " 9.  Unlock Account"
echo " 10. Detail Account"
echo " 11. Change Limit IP"
echo " 12. Change Limit Quota"
echo " x.  Exit"
echo "======================================"
echo
read -p "Enter your option [1-12 or x] : " opt
case $opt in
1) clear ; addtr ;;
2) clear ; trialtr ;;
3) clear ; renewtr ;;
4) clear ; deltr ;;
5) clear ; cek-logintr ;;
6) clear ; listusertr ;;
7) clear ; list-locktr ;;
8) clear ; locktr ;;
9) clear ; unlocktr ;;
10) clear ; usertr ;;
11) clear ; changeip-tr ;;
12) clear ; changequota-tr ;;
x) clear ; menu ;;
*) echo "You pressed it wrong!" ; sleep 1 ; m-trojan ;;
esac