#!/bin/bash
clear

NUMBER_OF_CLIENTS=$(grep -c -E "^#! " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		clear
    echo "======================================"
    echo " ❖ Renew Trojan Account"
    echo "--------------------------------------"
		echo " You have no existing clients!"
    echo "======================================"
    echo 
    read -n 1 -s -r -p "Press any key to back"
    m-trojan
	fi

	clear
  echo "======================================"
  echo " ❖ Renew Trojan Account"
  echo "--------------------------------------"
  printf " %-20s %s\n" "Username" "Exp Date"
  echo "--------------------------------------"
  grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq | while read -r user exp; do
    printf " %-20s %s\n" "$user" "$exp"
  done
  echo "======================================"
  echo
	read -rp "Enter username : " user

  if [ -z $user ]; then
    m-trojan
  else
    rm -f /etc/limit/trojan/ip/${user}
    rm -f /etc/trojan/$user
    read -p "Expired (days) : " masaaktif
    read -p "Limit User (GB): " Quota
    read -p "Limit User (IP): " iplim
    exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    mkdir -p /etc/limit/trojan/ip
    echo ${iplim} >> /etc/limit/trojan/ip/${user}

if [ ! -e /etc/trojan/ ]; then
  mkdir -p /etc/trojan/
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $masaaktif))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "/#! $user/c\#! $user $exp4" /etc/xray/config.json
    sed -i "/#! $user/c\#! $user $exp4" /root/akun/trojan/.trojan.conf
    systemctl restart xray > /dev/null 2>&1
    clear
    echo "======================================"
    echo " ❖ Renew Trojan Account"
    echo "--------------------------------------"
    echo " Client Name : $user"
    echo " Expired     : $exp4"
    echo " Limit Quota : $Quota"
    echo " Limit IP    : $iplim"
    echo "======================================"
    echo
    read -n 1 -s -r -p "Press any key to back"
    m-trojan
fi