#!/bin/bash
clear

restart_all_services() {
echo "======================================"
echo " ❖ Restat All Service"
echo "--------------------------------------"
echo -e " Restarting Fail2ban"
systemctl restart fail2ban 2>/dev/null
sleep 0.5
echo -e " Restarting Cron"
systemctl restart cron 2>/dev/null
sleep 0.5
echo -e " Restarting Nginx"
systemctl restart nginx 2>/dev/null
sleep 0.5
echo -e " Restarting Xray"
systemctl restart xray 2>/dev/null
systemctl restart private 2>/dev/null
systemctl restart public 2>/dev/null
sleep 0.5
echo -e " Restarting Haproxy"
systemctl restart haproxy 2>/dev/null
sleep 0.5
echo -e " Restarting Slow DNS"
systemctl restart server-sldns 2>/dev/null
sleep 0.5
echo -e " Restarting UDP Custom"
systemctl restart udp-custom 2>/dev/null
sleep 0.5
echo -e " Restarting Noobz VPN"
systemctl restart noobzvpns 2>/dev/null
sleep 0.5
echo -e " Restarting ZiVPN"
systemctl restart zivpn 2>/dev/null
sleep 0.5
echo -e " All Service Restarted"
echo "======================================"
echo
read -n 1 -s -r -p "Press any key to back"
m-setting
}

restart_all_services
