#!/bin/bash
clear
echo "======================================"
echo " ❖ Restore VPS Data"
echo "--------------------------------------"
echo " This feature can only be used if you use this autoscript."
echo " Please input link to your vps data backup file."
echo " You can check it on your email if you run backup data vps before."
echo "--------------------------------------"
read -rp " Link File: " url

wget -O backup.zip "$url"
unzip backup.zip
rm -f backup.zip
sleep 1
cd /root/backup
cp passwd /etc/
cp group /etc/
cp shadow /etc/
cp gshadow /etc/
cp -r xray /etc/
cp -r html /var/www/
cp crontab /etc/
cp .vmess.db /etc/vmess/
cp .vless.db /etc/vless/
cp .trojan.db /etc/trojan/
cp .shadowsocks.db /etc/shadowsocks/
cp -r limit /etc/
cp -r vmess /etc/
cp -r trojan /etc/
cp -r vless /etc/
cp -r shadowsocks /etc/
cp -a detail/. /detail/
rm -rf /root/backup
rm -f backup.zip

echo "Restore Success!!!" | lolcat
read -n 1 -s -r -p "Press any key to back"
m-backup