#!/bin/bash
clear
if ! command -v at &> /dev/null; then
  apt update && sudo apt install -y at
	systemctl enable --now atd
fi
clear
echo "======================================"
echo " ❖ Create Trial Vless Account"
echo "--------------------------------------"
echo " Input number only [ex: 30] for 30 min"
echo "--------------------------------------"
echo

while true; do
    read -p "Enter minutes : " pup
    if [[ "$pup" =~ ^[0-9]+$ ]]; then
        break
    else
        echo "Please Input Numbers Only"
    fi
done

Login=Trial
masaaktif=1
iplimit=1
Quota=1
user="${Login}VL$(tr -dc 0-9 </dev/urandom | head -c3)"
domain=$(cat /etc/xray/domain)
uuid=$(cat /proc/sys/kernel/random/uuid)
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws&host=${domain}&sni=${domain}#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws&host=${domain}#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [[ $iplimit -gt 0 ]]; then
  mkdir -p /etc/limit/vless/ip
  echo -e "$iplimit" > /etc/limit/vless/ip/$user
else
  echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^#&" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "#& ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db
systemctl restart xray > /dev/null 2>&1
echo sed -i \"/$user/d\" /etc/xray/config.json  | at now + $pup minutes
mkdir -p /detail/vless/

cat > /detail/vless/$user.txt <<-END
=========
Trial Vless Account
=========
Remarks     : ${user}
Domain      : ${domain}
User Quota  : ${Quota} GB
User IP     : ${iplimit} IP
Port nTLS   : 80,8080,2086,8880
Port TLS    : 443,8443
User ID     : ${uuid}
Path TLS    : /vless/multi-path
ServiceName : vless-grpc
=========
Link TLS    : ${vlesslink1}
=========
Link nTLS   : ${vlesslink2}
=========
Link GRPC   : ${vlesslink3}
=========
Open Clash : https://${domain}:81/vless-$user.txt
=========
Create at  : $tnggl
Expired    : $pup Minutes
=========
END

cat >/var/www/html/vless-$user.txt <<-END
=========
Format Open Clash
=========
- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

=========
Link TLS      : 
${vlesslink1}
=========
Link nTLS     : 
${vlesslink2}
=========
Link GRPC     : 
${vlesslink3}
=========
Create at     : $tnggl
Expired       : $pup Minutes
=========
END

function notif_vl() {
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    export TIME="10"
    export URL="https://api.telegram.org/bot$KEY/sendMessage"
    sensor=$(echo "$user" | sed 's/\(.\{3\}\).*/\1xxx/')
    ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
    TEXT="
<b>=========</b>
<b>❖ TRANSACTION SUCCESSFULL  </b>
<b>=========</b>
<b>Product     :</b> Trial Vless
<b>ISP         :</b> <code>${ISP}</code>
<b>Limit Quota :</b> <code>${Quota} GB</code>
<b>Limit Login :</b> <code>${iplimit} IP</code>
<b>Username    :</b> <code>${sensor}</code>
<b>Duration    :</b> <code>${pup} Minutes</code>
<b>=========</b>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

notif_vl
clear
echo -e "========="
echo -e "Trial Vless Account"
echo -e "========="
echo -e "Remarks     : ${user}"
echo -e "Domain      : ${domain}"
echo -e "User Quota  : ${Quota} GB"
echo -e "User IP     : ${iplimit} IP"
echo -e "Port nTLS   : 80,8080,2086,8880"
echo -e "Port TLS    : 443,8443"
echo -e "User ID     : ${uuid}"
echo -e "Path TLS    : /vless/multi-path "
echo -e "ServiceName : vless-grpc"
echo -e "========="
echo -e "Link TLS    : ${vlesslink1}"
echo -e "========="
echo -e "Link NTLS   : ${vlesslink2}"
echo -e "========="
echo -e "Link GRPC   : ${vlesslink3}"
echo -e "========="
echo -e "Open Clash  : https://${domain}:81/vless-$user.txt"
echo -e "========="
echo -e "Create at   : $tnggl"
echo -e "Expired     : $pup Minutes"
echo -e "========="
echo
read -n 1 -s -r -p "Press any key to back"
m-vless