#!/bin/bash
clear
echo "============================================"
echo " ❖ Unlock SSH Account"
echo "--------------------------------------------"
echo " Username         Exp Date         Status "
echo "--------------------------------------------"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
  if [[ "$status" = "L" ]]; then
    printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     " "LOCKED"
  else
    printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     " "UNLOCKED"
  fi
fi
done < /etc/passwd
echo "--------------------------------------------"
echo
read -p "Enter username : " username
egrep "^$username" /etc/passwd >/dev/null
passwd -u $username
clear
echo "======================================"
echo " ❖ Unlock SSH Account"
echo "--------------------------------------"
echo " Account $username has been unlocked!"
echo "======================================"
echo
read -n 1 -s -r -p "Press any key to back"
m-ssh