#!/bin/bash
clear
echo "======================================"
echo " ❖ Detail SSH Account"
echo "--------------------------------------"
echo " No   Username         Exp Date"
echo "--------------------------------------"

users=""
i=1 # Variabel penghitung untuk nomor urut

while read expired; do
    AKUN="$(echo $expired | cut -d: -f1)"
    ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
    exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
    status="$(passwd -S $AKUN | awk '{print $2}')"
    if [[ $ID -ge 1000 ]]; then
        users+="$AKUN "
        if [[ "$status" = "L" ]]; then
            printf "%-3s %-17s %2s %-17s %2s \n" "$i)" "$AKUN" "$exp"
        else
            printf "%-3s %-17s %2s %-17s %2s \n" "$i)" "$AKUN" "$exp"
        fi
        ((i++)) # Increment angka untuk user berikutnya
    fi
done < /etc/passwd

if [[ -z "$users" ]]; then
    clear
    echo "======================================"
    echo " ❖ Detail SSH Account"
    echo "--------------------------------------"
    echo " No users found in the configuration file"
    echo "======================================"
    echo
    read -n 1 -s -r -p "Press any key to back"
    m-ssh
fi

echo "======================================"
echo
read -p "Enter number : " number

if ! [[ "$number" =~ ^[0-9]+$ ]]; then
    echo "Invalid input. Please enter a number"
    read -n 1 -s -r -p "Press any key to back"
    m-ssh
fi

selected_user=$(echo $users | awk -v n="$number" '{print $n}')

if [ -z "$selected_user" ]; then
    echo -e "Number is missing or incorrect."
    read -n 1 -s -r -p "Press any key to back"
    m-ssh
fi

detail_file="/detail/ssh/$selected_user.txt"
if [[ -f "$detail_file" ]]; then
    clear
    echo "======================================"
    echo " ❖ Detail SSH Account"
    echo "--------------------------------------"
    cat "$detail_file"
    echo "======================================"
    echo
    read -n 1 -s -r -p "Press any key to back"
    m-ssh
else
    echo "Detail file not found for user: $selected_user"
    read -n 1 -s -r -p "Press any key to back"
    m-ssh
fi