#!/bin/bash

echo "======================================"
echo " ❖ Detail Noobz VPN Account"
echo "--------------------------------------"

config_file="/etc/noobzvpns/.noobzvpns"
if [[ ! -f "$config_file" ]]; then
    echo -e "Config file not found: $config_file"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
fi

accounts=$(grep -E "^#nob# " "$config_file" | awk '{print $2, $3}' | sort -u)

if [[ -z "$accounts" ]]; then
    echo -e "No accounts found in configuration"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
fi

i=1
declare -a account_array
echo -e "No   Username          Exp Date"
while read -r AKUN exp; do
    if [[ -n "$AKUN" && -n "$exp" ]]; then
        printf "%-4s %-17s %-17s\n" "$i)" "$AKUN" "$exp"
        account_array+=("$AKUN")
        ((i++))
    fi
done <<< "$accounts"


if [[ ${#account_array[@]} -eq 0 ]]; then
    echo -e "No valid accounts found"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
fi

echo "======================================"
echo ""
read -p "Enter Number: " number

if [[ -z "$number" || ! "$number" =~ ^[0-9]+$ ]]; then
    echo -e "Invalid input. Please enter a valid number"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
fi

if (( number < 1 || number > ${#account_array[@]} )); then
    echo -e "Number is out of range. Please select a valid number"
    read -n 1 -s -r -p "Press any key to back"
    m-nob
fi

selected_user="${account_array[$((number - 1))]}"
echo "DEBUG: Selected User: ${selected_user}"

detail_file="/detail/nob/$selected_user.txt"
if [[ -f "$detail_file" ]]; then
    clear
    echo "======================================"
    echo " ❖ Detail Noobz VPN Account"
    echo "--------------------------------------"
    cat " $detail_file"
    echo "======================================"
    echo
    read -n 1 -s -r -p "Press any key to back"
    m-nob
else
    clear
    echo "======================================"
    echo " ❖ Detail Noobz VPN Account"
    echo "--------------------------------------"
    echo " Detail file not found for user: $selected_user"
    echo "======================================"
    echo
    read -n 1 -s -r -p "Press any key to back"
    m-nob
fi