#!/bin/bash
# Main Configuration
DOMAIN=hahah.fun # Your Domain
CF_KEY=266a89fba5c8824b989d663b382ba84f06d17 # Cloudflare Global Api Key
CF_ID=qwqw34207@gmail.com # Email Cloudflare
#-------------------

clear
IP=$(wget -qO- icanhazip.com)
apt install jq curl -y >/dev/null 2>&1
clear
echo ""
echo "======================================"
echo " ❖ Setup Subdomain Menu"
echo "--------------------------------------"

set -euo pipefail

ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}&status=active" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" | jq -r .result[0].id)

echo " Domain Available: tomatovpn.my.id"
echo " Ex Subdomain: test123"
echo "======================================"
echo ""
read -p "Enter Subdomain : " domen

sub=${domen}
dns=${sub}.${DOMAIN}
nameserver="ns-${sub}.${DOMAIN}"

EXISTING_SUB=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?type=A&content=${IP}" \
    -H "X-Auth-Email: ${CF_ID}" \
    -H "X-Auth-Key: ${CF_KEY}" \
    -H "Content-Type: application/json" | jq -r '.result[0].name')

if [[ "$EXISTING_SUB" != "null" && "$EXISTING_SUB" != "$dns" ]]; then
    echo "IP ${IP} already used by subdomain: ${EXISTING_SUB}"
    dns=$EXISTING_SUB
    sub=$(echo "$dns" | cut -d. -f1)
    nameserver="ns-${sub}.${DOMAIN}"
    echo "Will use the old subdomain."
fi

RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${dns}" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" | jq -r .result[0].id)

if [[ "${#RECORD}" -le 10 ]]; then
     RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"type":"A","name":"'${dns}'","content":"'${IP}'","ttl":120,"proxied":false}' | jq -r .result.id)
fi

curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"type":"A","name":"'${dns}'","content":"'${IP}'","ttl":120,"proxied":false}' >/dev/null

echo "Setting NS Record For ${nameserver}"

NS_RECORD_ID=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?type=NS&name=${nameserver}" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" | jq -r .result[0].id)

if [[ "${#NS_RECORD_ID}" -le 10 ]]; then
     NS_RECORD_ID=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"type":"NS","name":"'${nameserver}'","content":"'${dns}'","ttl":120,"proxied":false}' | jq -r .result.id)
else
     echo -e "${BIWhite}NS record ${nameserver} sudah ada, tidak dibuat ulang.${NC}"
fi

curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${NS_RECORD_ID}" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"type":"NS","name":"'${nameserver}'","content":"'${dns}'","ttl":120,"proxied":false}' >/dev/null

echo "$dns" > /root/domain
echo "$dns" > /etc/xray/domain
echo "$nameserver" > /root/nsdomain
echo "$nameserver" > /etc/xray/dns
echo "IP=$dns" > /var/lib/ipvps.conf
cd